Repository suyashkumar/dicom, pull requests merged in 2020-12, with the labels that each got.

#149 Add -version flag to dicomutil
  .gitignore
  Makefile
  cmd/dicomutil/main.go
Labels: enhancement

#153 Initial support for AT Tag
  read.go
  write.go
  write_test.go
Labels: enhancement

#159 Add dedicated Benchmark GitHub actions and cleanup Build Action.
  .github/workflows/bench_pr.yml
  .github/workflows/bench_push.yml
  .github/workflows/go.yml
Labels: enhancement, performance

#160 Add comprehensive benchmarks and tests for readNativeFrames
  read.go
  read_test.go
Labels: performance

#157 Reduce allocations during readNativeFrames, leading to ~15-20% performance improvement
  Makefile
  read.go
  read_test.go
Labels: performance

#163 Use a once-allocated buffer for reading native pixel values instead of using binary.Read (which allocates a slice under the hood)
  mocks/pkg/dicomio/mock_reader.go
  pkg/dicomio/reader.go
  read.go
  read_test.go
Labels: enhancement, performance

#170 Add more expansive write native PixelData tests, cleanup internals.
  write.go
  write_test.go
Labels: enhancement
